constants:
  path_video: './Number-detection/Enter_system/src/record.mp4'
  frame_size: [2258,1244]
  frame_rate: 20
  coord: [[0,0], [0,1], [1,0], [1,1]]
  path_enter_car: './Number-detection/Enter_system/src/enter_car.txt'